//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUTHU()
        {
            this.ITEMs = new HashSet<ITEM>();
        }
    
        public int ID { get; set; }
        public string IDDOIBONG { get; set; }
        public Nullable<int> IDQUOCTICH { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> TUOI { get; set; }
        public Nullable<int> SOGIAI { get; set; }
        public Nullable<int> SOBANTHANG { get; set; }
        public string HINHANH { get; set; }
        public string CHANTHUAN { get; set; }
        public string THETRANG { get; set; }
        public string VITRI { get; set; }
        public Nullable<int> SOAO { get; set; }
        public string CHIEUCAO { get; set; }
        public string CANNANG { get; set; }
        public Nullable<long> GIATRICAUTHU { get; set; }
    
        public virtual DOIBONG DOIBONG { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
    }
}
