//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOIBONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOIBONG()
        {
            this.CAUTHUs = new HashSet<CAUTHU>();
            this.DIEMs = new HashSet<DIEM>();
            this.ITEMs = new HashSet<ITEM>();
            this.TEAMOFLEAGUEs = new HashSet<TEAMOFLEAGUE>();
            this.THONGTINTRANDAUs = new HashSet<THONGTINTRANDAU>();
        }
    
        public string ID { get; set; }
        public Nullable<int> IDQUOCTICH { get; set; }
        public Nullable<int> THANHPHO { get; set; }
        public byte[] HINHANH { get; set; }
        public string TEN { get; set; }
        public Nullable<int> SOLUONGTHANHVIEN { get; set; }
        public Nullable<System.DateTime> NGAYTHANHLAP { get; set; }
        public string SANNHA { get; set; }
        public string SODOCHIENTHUAT { get; set; }
        public string GIATRI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAUTHU> CAUTHUs { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAMOFLEAGUE> TEAMOFLEAGUEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINTRANDAU> THONGTINTRANDAUs { get; set; }
    }
}
