//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOTBALLMATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOTBALLMATCH()
        {
            this.THONGTINTRANDAUs = new HashSet<THONGTINTRANDAU>();
        }
    
        public int ID { get; set; }
        public string TENTRANDAU { get; set; }
        public Nullable<int> VONGBANG { get; set; }
        public Nullable<int> IDVONG { get; set; }
        public Nullable<int> DIADIEM { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    
        public virtual DIADIEM DIADIEM1 { get; set; }
        public virtual ROUND ROUND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINTRANDAU> THONGTINTRANDAUs { get; set; }
    }
}
