//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAIDAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAIDAU()
        {
            this.DIEMs = new HashSet<DIEM>();
            this.TRANDAUs = new HashSet<TRANDAU>();
            this.THONGTINGIAIDAUs = new HashSet<THONGTINGIAIDAU>();
            this.VONGDAUs = new HashSet<VONGDAU>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDQUOCGIA { get; set; }
        public byte[] HINHANH { get; set; }
        public string TEN { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<int> SODOITG { get; set; }
        public string QUOCGIA
        {
            get
            {
                var qg = DataProvider.ins.DB.QUOCTICHes.Find(IDQUOCGIA);

                return qg == null ? " " : qg.TENQUOCGIA;
            }
            set { }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANDAU> TRANDAUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINGIAIDAU> THONGTINGIAIDAUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VONGDAU> VONGDAUs { get; set; }
    }
}
