//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMOFLEAGUE
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAMOFLEAGUE()
        {
            this.THONGTINTRANDAUs = new HashSet<THONGTINTRANDAU>();
        }
    

        public int ID { get; set; }
        public Nullable<int> IDGIAIDAU { get; set; }
        public string IDDOIBONG { get; set; }
    

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINTRANDAU> THONGTINTRANDAUs { get; set; }

        public virtual DOIBONG DOIBONG { get; set; }
        public virtual LEAGUE LEAGUE { get; set; }

    }
}
